### ISSUE TITLE
New page should show snippet views of blog posts

### ISSUE THREAD

**Issue by dmratzan** [roman-gardens/gre-archive-2025-06-04#164]
Can we have the default behavior of this page work like gardens and show a few lines of each blog post and the date posted?

**Comment by christiancasey** [comment]
Did you put _index.md?

**Comment by christiancasey** [comment]
You did not!

**Comment by christiancasey** [comment]
I'll put it

**Comment by dmratzan** [comment]
thanks. If it is ok, I think we should remove the hack to get the snippet, since this page will be shared more than navigated to. Is that OK?
